### ISSUE TITLE
Build failure with dmd 2.066

### ISSUE THREAD

**Issue by mrkline** [rejectedsoftware/ddox#53]
ddox pulls in vibe v0.7.20, which fails to build on dmd 2.066. After tweaking `package.json` so that it uses the master branch of vibe (`"vibe-d": "~master"`), we are met with the following:

```
Compiling diet template 'ddox.overview.dt' (compat)...
/usr/include/dlang/dmd/core/stdc/stdarg.d(215): Error: 'std.variant.VariantN!32LU.VariantN.opAssign!(VariantN!32LU).opAssign' is not nothrow
/usr/include/dlang/dmd/core/stdc/stdarg.d(205): Error: function 'core.stdc.stdarg.va_arg!(VariantN!32LU).va_arg' is nothrow yet may throw
/usr/include/dlang/dmd/core/stdc/stdarg.d(201): Error: template instance core.stdc.stdarg.va_arg!(VariantN!32LU) error instantiating
../.dub/packages/vibe-d-master/source/vibe/templ/diet.d-mixin-105(107):        instantiated from here: va_arg!(VariantN!32LU)
../.dub/packages/vibe-d-master/source/vibe/templ/diet.d(93):        instantiated from here: compileDietFileCompatV!("ddox.overview.dt", HTTPServerRequest, "req", DocPageInfo, "info")
source/ddox/htmlgenerator.d(249):        instantiated from here: compileDietFileCompat!("ddox.overview.dt", HTTPServerRequest, "req", DocPageInfo, "info")
```
